swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
  - name: "user"
    description: "Operations about user"
schemes:
  - "https"
  - "http"
paths:
  /user/login:
    post:
      tags:
        - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "LoginUser"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object"
          required: true
          schema:
            $ref: "#/definitions/UserLogin"
      responses:
        default:
          description: "successful operation"
  /user/cadastro:
    post:
      tags:
        - "user"
      summary: "Creates list of users with given input array"
      description: ""
      operationId: "createUser"
      parameters:
        - in: "body"
          name: "body"
          description: "List of user object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
definitions:
  User:
    type: object
    properties:
      nome:
        type: string
      cpf/cnpj:
        type: string
      email:
        type: string
      password:
        type: string
      contato:
        type: string
      endereco:
        type: string
      cidade:
        type: string
      bairro:
        type: string
      estado:
        type: string
      cep:
        type: string

  UserLogin:
    type: object
    properties:
      login:
        type: string
      pass:
        type: string